name: Deploy

on:
  push:
  pull_request:

jobs:
  test_deploy:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
          MYSQL_USER: root
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 8.0]
        laravel: [^8.0]

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install Preflight
        run: |
          composer create-project laravel/laravel preflight
          cd preflight
          composer require cratespace/preflight
          php artisan preflight:install
          php artisan key:generate
          npm i && npm run dev && npm run test
          php artisan migrate:fresh --seed

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./preflight/storage/logs
