name: Deploy

on:
  push:
  pull_request:

jobs:
  test_deploy:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 8.0]
        laravel: [^8.0]

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install Preflight
        run: |
          composer create-project laravel/laravel preflight
          cd preflight
          composer require cratespace/preflight
          php artisan preflight:install
          php artisan key:generate
          npm i && npm run dev && npm run test
          php artisan test

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./preflight/storage/logs
